"""init

Revision ID: 0a92dbff9d1c
Revises: 
Create Date: 2026-08-12 16:31:57.068822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a92dbff9d1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('path_image', sa.String(), nullable=True),
    sa.Column('link_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculumvitae',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagesme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informationme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('information', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_project', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('completion_data', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('project_number', sa.Integer(), nullable=True),
    sa.Column('level_advanced', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link_page', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readmore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('numeric', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('numeric', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('path_image', sa.String(), nullable=True),
    sa.Column('link_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('filesproject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_project', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagesmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_message', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_message'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagesproject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_project', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologiesproject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_project', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technologiesproject')
    op.drop_table('imagesproject')
    op.drop_table('imagesmessage')
    op.drop_table('filesproject')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('tools')
    op.drop_table('readmore')
    op.drop_table('projects')
    op.drop_table('jobs')
    op.drop_table('informationme')
    op.drop_table('imagesme')
    op.drop_table('curriculumvitae')
    op.drop_table('contact')
    op.drop_table('aboutme')
    # ### end Alembic commands ###
