"""add started_at and is_support to projects

Revision ID: 13e1c0c602cf
Revises: a0eaa9246078
Create Date: 2026-08-23 20:52:59.333946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e1c0c602cf'
down_revision: Union[str, Sequence[str], None] = 'a0eaa9246078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('started_at', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('is_support', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_support')
    op.drop_column('projects', 'started_at')
    # ### end Alembic commands ###
