---
- name: Clone or update repository (via PAT, HTTPS)
  ansible.builtin.git:
    repo: "https://{{ github_pat }}@github.com/arturscibor/arturscibor_backend.git"
    dest: "{{ repo_dest }}"
    version: main
    force: true

- name: Remove PAT from git remote after checkout
  ansible.builtin.command:
    cmd: "git remote set-url origin {{ repo_url }}"
    chdir: "{{ repo_dest }}"
  changed_when: true
