---
- name: Deploy arturscibor_backend
  hosts: production
  become: true
  vars_files:
    - secrets.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    repo_url: "https://github.com/arturscibor/arturscibor_backend.git"
    repo_dest: /opt/arturscibor_backend
    doppler_project: arturscibor_backend
    doppler_config: prd
  tasks:
    - import_tasks: tasks/checkout.yml
    - import_tasks: tasks/networks.yml
    - import_tasks: tasks/secret_env.yml
    - import_tasks: tasks/deploy.yml
    - import_tasks: tasks/cleanup.yml
